config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :profiles do 
  	member do 
  		get :myprofile
  	end 
  end 

  root 'profiles#index'
  
  devise_for :users, 
  :controllers => {
                :registrations => "client/registrations"
            }
  resources :users

  resources :conversations do
  	resources :messages
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord

	belongs_to :user

	validates :name, :presence => true
	validates :age, :presence => true
	validates :primary_instrument, :presence => true
	validates :city, :presence => true 
	validates :status, :presence => true
	validates :years_spent_playing, :presence => true 
	validates :looking_for, :presence => true 
	validates :state, :presence => true 
	validates :image, :presence => true 

	has_attached_file :image, styles: { normal: "500x360#", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png", default_style: :normal
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_attached_file :audioclip, { validate_media_type: false } 
  #validates_attachment_content_type :audioclip, content_type: ['audio/mp3','audio/mpeg']

  has_attached_file :audioclip2, { validate_media_type: false } 
  #validates_attachment_content_type :audioclip2, content_type: ['audio/mp3','audio/mpeg']

  has_attached_file :audioclip3, { validate_media_type: false } 
  #validates_attachment_content_type :audioclip3, content_type: ['audio/mp3','audio/mpeg']

  has_many :genres_profiles
	has_many :genres, :through => :genres_profiles

  	def instrument_image 
  		"#{self.primary_instrument}.png"
  	end 

  	def second_instrument_image 
  		"#{self.second_instrument}.png"
  	end 

  	def third_instrument_image 
  		"#{self.third_instrument}.png"
  	end 

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :new, :edit, :destroy, :create]
  before_action :set_user

  # GET /profiles
  # GET /profiles.json
  def index
    #profiles used for users who lack profiles
    @profiles = Profile.all.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 4)
    #users used for users who have added a profile 
    if user_signed_in?
      @users = User.joins(:profile).includes(:profile).where(profiles: {status: "Looking"}).order(last_sign_in_at: :desc).where.not(id: current_user.id).paginate(:page => params[:page], :per_page => 4) 
      if current_user.profile.nil? 
        if !params[:search_instrument].nil? 
          @profiles = @profiles.where("LOWER(profiles.primary_instrument) LIKE ?", "%#{params[:search_instrument].downcase}%")
        end
        if !params[:search_name].nil? 
          @profiles = @profiles.where("LOWER(profiles.name) LIKE ?", "%#{params[:search_name].downcase}%")
        end
        if !params[:search_city].nil? 
          @profiles = @profiles.where("LOWER(profiles.city) LIKE ?", "%#{params[:search_city].downcase}%")
        end
        if !params[:search_state].nil? 
          @profiles = @profiles.where("LOWER(profiles.state) LIKE ?", "%#{params[:search_state].downcase}%")
        end
      else 
         if !params[:search_instrument].nil? 
           @users = @users.where("LOWER(profiles.primary_instrument) LIKE ?", "%#{params[:search_instrument].downcase}%")
        end
        if !params[:search_name].nil? 
          @users = @users.where("LOWER(profiles.name) LIKE ?", "%#{params[:search_name].downcase}%")
        end
        if !params[:search_city].nil? 
          @users = @users.where("LOWER(profiles.city) LIKE ?", "%#{params[:search_city].downcase}%")
        end
        if !params[:search_state].nil? 
          @users = @users.where("LOWER(profiles.state) LIKE ?", "%#{params[:search_state].downcase}%")
        end
      end
    else 
      if !params[:search_instrument].nil? 
        @profiles = @profiles.where("LOWER(profiles.primary_instrument) LIKE ?", "%#{params[:search_instrument].downcase}%")
      end
      if !params[:search_name].nil? 
        @profiles = @profiles.where("LOWER(profiles.name) LIKE ?", "%#{params[:search_name].downcase}%")
      end
      if !params[:search_city].nil? 
        @profiles = @profiles.where("LOWER(profiles.city) LIKE ?", "%#{params[:search_city].downcase}%")
      end
      if !params[:search_state].nil? 
        @profiles = @profiles.where("LOWER(profiles.state) LIKE ?", "%#{params[:search_state].downcase}%")
      end
    end
  end

  def show
    @user = @profile.user
  end
  
  def new
      @profile = Profile.new
  end

  def edit
    @profile = current_user.profile
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = @user 

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to myprofile_profile_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def myprofile
    @profile = @user.profile
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def set_user
      @user = current_user
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:audioclip, :audioclip2, :audioclip3, :years_spent_playing, :user_id, :name, :bio, :age, :city, :state, :primary_instrument, :second_instrument, :third_instrument, :status, :looking_for, :image, :genre => [])
    end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for @profile do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :image, as: :file %>
  <%= f.input :status, collection: ['Looking', 'Unavailable'] %>
  <%= f.input :city %>
  <%= f.input :state, collection: [
      'Alabama', 
      'Alaska', 
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut', 
      'Delaware', 
      'District of Columbia', 
      'Florida', 
      'Georgia', 
      'Hawaii', 
      'Idaho', 
      'Illinois', 
      'Indiana', 
      'Iowa', 
      'Kansas', 
      'Kentucky', 
      'Louisiana', 
      'Maine', 
      'Maryland', 
      'Massachusetts', 
      'Michigan',
      'Minnesota', 
      'Mississippi', 
      'Missouri', 
      'Montana', 
      'Nebraska', 
      'Nevada', 
      'New Hampshire', 
      'New Jersey', 
      'New Mexico', 
      'New York', 
      'North Carolina', 
      'North Dakota', 
      'Ohio', 
      'Oklahoma', 
      'Oregon', 
      'Pennsylvania', 
      'Puerto Rico', 
      'Rhode Island', 
      'South Carolina', 
      'South Dakota', 
      'Tennessee', 
      'Texas', 
      'Utah', 
      'Vermont', 
      'Virginia', 
      'Washington', 
      'West Virginia',
      'Wisconsin', 
      'Wyoming'
    ], label: "State" %>
  <%= f.input :primary_instrument, collection: ['Bass','Drums','Guitar','Harmonica','Keyboard','Piano','Violin', 'Other'], label: "Primary Instrument" %>
  <%= f.input :second_instrument, collection: ['Bass','Drums','Guitar','Harmonica','Keyboard','Piano','Violin', 'Other'], label: "Second Instrument (if applicable)"  %>
  <%= f.input :third_instrument, collection: ['Bass','Drums','Guitar','Harmonica','Keyboard','Piano', 'Violin', 'Other'], label: "Third Instrument (if applicable)"  %>
  <%= f.input :looking_for, collection: ['Band', 'Bass','Drums','Guitar','Harmonica','Keyboard','Piano','Violin', 'Other'], label: 'Looking For' %>
  <%= f.input :years_spent_playing %>
  <%= f.input :bio, :as => :text, :input_html => {:rows => 5} %>
  <%= f.input :audioclip, as: :file, label: "Audio Clip" %> 
  <%= f.input :audioclip2, as: :file, label: "Audio Clip 2" %> 
  <%= f.input :audioclip3, as: :file, label: "Audio Clip 3" %> 
  <br />
  <%= f.button :submit, class: 'btn btn-purple top_spacing' %>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2">
		<br /><br />
		<h2>Edit Profile</h2>
		<br />
		<%= render 'form', profile: @profile %>
		<br /><br /><br /><br />
	</div>
</div>

app/views/profiles/index.html.erb
  <div class="row index_row">
    <div class="col-sm-4 col-sm-push-1 col-lg-3 col-lg-push-2 index_profile searchbar">
      <h3><i class="fa fa-search"></i> Search</h3>
           <%= form_tag profiles_path, :method=> 'get' do %>
          <div class="form-group">
            <label for="search_instrument">Instrument</label><br />
            <%= text_field_tag :search_instrument, params[:search_instrument], class: "form-control searchbar_fields" %>
            <br />
            <label for="search_name">Name</label>
            <br />
            <%= text_field_tag :search_name, params[:search_name], class: "form-control searchbar_fields" %>
            <br />
            <label for="search_city">City</label>
            <br />
            <%= text_field_tag :search_city, params[:search_city], class: "form-control searchbar_fields" %>
            <br />
            <label for="search_state">State</label>
            <br />
            <%= text_field_tag :search_state, params[:search_state], class: "form-control searchbar_fields" %>
            <br />
            <%= submit_tag "Search", class: "btn btn-purple2" %>
          </div>
        <% end %>
        
    </div>
    <div class='col-sm-8 col-lg-7 col-lg-push-1'>
      <br />
      <% if user_signed_in? %> 
        <% if current_user.profile.nil? %>
         <% @profiles.each do |profile| %>
            <% if profile.status=="Looking" %>
              <div class="col-sm-12">
                <a href="/profiles/<%= profile.id %>">
                  <div class="col-xs-10 col-xs-push-1 col-sm-9 col-sm-push-2 index_profile">
                    <div class="col-sm-6">
                        <%= image_tag profile.image.url(:normal), class: "index_image" %>
                    </div>
                     <div class="col-sm-6">
                      <p class="index_info_name"><b><%= profile.name %></b><br /></p>
                        <div class="years_spent_playing_container_index">
                            <p><%= profile.years_spent_playing %></p>
                        </div>
                        <div class="info_container">
                          <%= image_tag profile.instrument_image, class: "instrument_image_index" %> 
                        </div>
                        <% if !profile.second_instrument.empty? %>
                          <div class="info_container">
                            <%= image_tag profile.second_instrument_image, class: "instrument_image_index" %> 
                          </div>  
                        <% end %> 
                        <% if !profile.third_instrument.empty? %>
                          <div class="info_container">
                            <%= image_tag profile.third_instrument_image, class: "instrument_image_index" %> 
                          </div>  
                        <% end %> 
                      <p class="index_info">
                      <b>Instrument: </b><%= profile.primary_instrument %><br />
                      <b>Looking For: </b><%= profile.looking_for %><br />
                      <b>City: </b><%= profile.city %><br />
                      <b>State: </b><%= profile.state %><br /></p>
                    </div>
                  </div>
                </a>
              </div>
            <% end %>
          <% end %>
        <% else %> 
          <% @users.each do |u| %>
              <div class="col-sm-12">
                <a href="/profiles/<%= u.profile.id %>">
                  <div class="col-xs-10 col-xs-push-1 col-sm-9 col-sm-push-2 index_profile">
                    <div class="col-sm-6">
                        <%= image_tag u.profile.image.url(:normal), class: "index_image" %>
                    </div>
                    <div class="col-sm-6">
                      <p class="index_info_name"><b><%= u.profile.name %></p>
                      <div class="years_spent_playing_container_index">
                        <p><%= u.profile.years_spent_playing %></p>
                      </div>
                      <div class="info_container">
                        <%= image_tag u.profile.instrument_image, class: "instrument_image_index" %> 
                      </div>
                      <% if !u.profile.second_instrument.empty? %>
                        <div class="info_container">
                          <%= image_tag u.profile.second_instrument_image, class: "instrument_image_index" %> 
                        </div>  
                      <% end %> 
                      <% if !u.profile.third_instrument.empty? %>
                        <div class="info_container">
                          <%= image_tag u.profile.third_instrument_image, class: "instrument_image_index" %> 
                        </div>  
                      <% end %> 
                      <p class="index_info">
                      <b>Looking For: </b><%= u.profile.looking_for %><br />
                      <b>City: </b><%= u.profile.city %><br />
                      <b>State: </b><%= u.profile.state %><br />
                      </p>
                    </div>
                  </div>
                 </a>    
              </div>    
          <% end %>
        <% end %>
      <% else %>
      <% @profiles.each do |profile| %> <!--not logged in-->
            <% if profile.status=="Looking" %>
              <div class="col-sm-12">
                <a href="/profiles/<%= profile.id %>">
                  <div class="col-xs-10 col-xs-push-1 col-sm-9 col-sm-push-2 index_profile">
                    <div class="col-sm-6">
                        <%= image_tag profile.image.url(:normal), class: "index_image" %>
                    </div>
                     <div class="col-sm-6">
                      <p class="index_info_name"><b><%= profile.name %></b><br /></p>
                        <div class="years_spent_playing_container_index">
                            <p><%= profile.years_spent_playing %></p>
                        </div>
                        <div class="info_container">
                          <%= image_tag profile.instrument_image, class: "instrument_image_index" %> 
                        </div>
                        <% if !profile.second_instrument.empty? %>
                          <div class="info_container">
                            <%= image_tag profile.second_instrument_image, class: "instrument_image_index" %> 
                          </div>  
                        <% end %> 
                        <% if !profile.third_instrument.empty? %>
                          <div class="info_container">
                            <%= image_tag profile.third_instrument_image, class: "instrument_image_index" %> 
                          </div>  
                        <% end %> 
                      <p class="index_info">
                      <b>Instrument: </b><%= profile.primary_instrument %><br />
                      <b>Looking For: </b><%= profile.looking_for %><br />
                      <b>City: </b><%= profile.city %><br />
                      <b>State: </b><%= profile.state %><br /></p>
                    </div>
                  </div>
                </a>
              </div>
            <% end %>
          <% end %>
      <% end %>
      <div class="col-xs-10 col-xs-push-1 col-sm-9 col-sm-push-2">
        <%= will_paginate @users, class: "apple_pagination" %>
      </div>
    </div>
  </div>

app/views/profiles/myprofile.html.erb
<div class="row profile_row">
	<div class="col-sm-4 col-sm-push-1 col-xs-10 col-xs-push-1">
		<%= image_tag @profile.image.url(:normal), class: 'block profile_pic' %>
		<% if !@profile.years_spent_playing.nil? %>
			<div class="years_spent_playing_container">
				<p><%= @profile.years_spent_playing %></p>
			</div>
		<% else %> 
		<% end %>
		<div class="info_container">
				<%= image_tag @profile.instrument_image, class: "instrument_image" %> 
		</div>
		<% if !@profile.second_instrument.empty? %>
			<div class="info_container">
					<%= image_tag @profile.second_instrument_image, class: "instrument_image" %> 
			</div>	
		<% end %> 
		<% if !@profile.third_instrument.empty? %>
			<div class="info_container">
					<%= image_tag @profile.third_instrument_image, class: "instrument_image" %> 
			</div>	
		<% end %> 
		<br />
		<h3><%= @profile.name %></h3>
		<p><b>Age: </b><%= @profile.age %></p>
		<p><b>City: </b><%= @profile.city %></p>
		<p><b>State: </b><%= @profile.state %></p>
		<p><b>Instrument: </b><%= @profile.primary_instrument %></p>
		<% if @profile.status=="Looking" %>
			<p><b>Looking For: </b><%= @profile.looking_for %></p>
		<% else %> 
			<p><b>Status: </b><%= @profile.status %></p>
		<% end %> 
		<p><b>Bio: </b><%= @profile.bio %></p>
		<br />
		<%= link_to "Edit Profile", edit_profile_path(current_user), class: 'btn btn-purple' %> 
		<br /><br /><br /><br /><br />
	</div>
	<div class="col-sm-4 col-sm-push-2 col-md-5 col-md-push-2 col-lg-5 col-xs-10 col-xs-push-1 sidebar">
		<h3>Uploads</h3>
		<% if !@profile.audioclip.blank? %>
			<a rel="alternate" type="application/rss+xml" title="RSS" href="<%= @profile.audioclip %>">
				<div class="upload_display">
						<p><%= @profile.audioclip_file_name.first(24) %></p>
				</div> 
			</a>
		<% else %>
			<div class="upload_display">
				<p>Sample #1</p>
			</div> 	
		<% end %> 
		<% if !@profile.audioclip2.blank? %>
			<a rel="alternate" type="application/rss+xml" title="RSS" href="<%= @profile.audioclip2 %>">
				<div class="upload_display">
					<p><%= @profile.audioclip2_file_name.first(24) %></p>
				</div> 
			</a>
		<% else %>
			<div class="upload_display">
				<p>Sample #2</p>
			</div> 	
		<% end %> 
		<% if !@profile.audioclip3.blank? %>
			<a rel="alternate" type="application/rss+xml" title="RSS" href="<%= @profile.audioclip3 %>">
				<div class="upload_display">
						<p><%= @profile.audioclip3_file_name.first(24) %></p>
				</div> 
			</a>
		<% else %>
			<div class="upload_display">
				<p>Sample #3</p>
			</div> 	
		<% end %> 
	</div>
</div>

app/views/profiles/new.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2">
		<br /><br />
		<h2>New Profile</h2>
		<br />
		<%= render 'form', profile: @profile %>
		<br /><br /><br /><br />
	</div>
</div>

app/views/profiles/show.html.erb
<div class="row profile_row">
	<div class="col-sm-4 col-sm-push-1 col-xs-10 col-xs-push-1">
		<%= image_tag @profile.image.url(:normal), class: "block profile_pic" %>
		<% if !@profile.years_spent_playing.nil? %>
			<div class="years_spent_playing_container">
				<p><%= @profile.years_spent_playing %></p>
			</div>
		<% else %> 
		<% end %>
		<div class="info_container">
				<%= image_tag @profile.instrument_image, class: "instrument_image" %> 
		</div>
		<% if !@profile.second_instrument.empty? %>
			<div class="info_container">
					<%= image_tag @profile.second_instrument_image, class: "instrument_image" %> 
			</div>	
		<% end %> 
		<% if !@profile.third_instrument.empty? %>
			<div class="info_container">
					<%= image_tag @profile.third_instrument_image, class: "instrument_image" %> 
			</div>	
		<% end %> 
		<br />
		<h3><%= @profile.name %></h3>
		<p><b>Age: </b><%= @profile.age %></p>
		<p><b>City: </b><%= @profile.city %></p>
		<p><b>State: </b><%= @profile.state %></p>
		<p><b>Instrument: </b><%= @profile.primary_instrument %></p>
		<% if @profile.status=="Looking" %>
			<p><b>Looking For: </b><%= @profile.looking_for %></p>
		<% else %> 
			<p><b>Status: </b><%= @profile.status %></p>
		<% end %> 
		<p><b>Bio: </b><%= @profile.bio %></p>
		<br />
		<% if current_user.profile != @profile && current_user.profile != nil %> 
			<button class="btn btn-purple" data-toggle="modal" data-target="#mynewmessage">Message</button>
		<% end %> 
		<br /><br /><br /><br /><br />
	</div>

	<div class="col-sm-4 col-sm-push-2 col-md-5 col-md-push-2 col-lg-5 col-lg-pus-0 col-xs-10 col-xs-push-1 sidebar">
		<h3>Uploads</h3>
		<% if !@profile.audioclip.blank? %>
			<a rel="alternate" type="application/rss+xml" title="RSS" href="<%= @profile.audioclip %>">
				<div class="upload_display">
						<p><%= @profile.audioclip_file_name.first(24) %></p>
				</div> 
			</a>
		<% else %>
			<div class="upload_display">
				<p>Sample #1</p>
			</div> 	
		<% end %> 
		<% if !@profile.audioclip2.blank? %>
			<a rel="alternate" type="application/rss+xml" title="RSS" href="<%= @profile.audioclip2 %>">
				<div class="upload_display">
					<p><%= @profile.audioclip2_file_name.first(24) %></p>
				</div> 
			</a>
		<% else %>
			<div class="upload_display">
				<p>Sample #2</p>
			</div> 	
		<% end %> 
		<% if !@profile.audioclip3.blank? %>
			<a rel="alternate" type="application/rss+xml" title="RSS" href="<%= @profile.audioclip3 %>">
				<div class="upload_display">
						<p><%= @profile.audioclip3_file_name.first(24) %></p>
				</div> 
			</a>
		<% else %>
			<div class="upload_display">
				<p>Sample #3</p>
			</div> 	
		<% end %> 
	</div>
	<% if current_user.profile != nil %>
		<div class="modal fade" id="mynewmessage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		    <div class="modal-dialog" role="document">
		        <div class="modal-content">

		         	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		            	<h4 class="modal-title" id="myModalLabel">Message to <%= @profile.name %></h4>
		            </div>
		            <div class="modal-body">
		                <%= form_tag conversations_path, method: :post do %>
							<%= hidden_field_tag(:user, "#{@user.id}") %>
						  	<%= hidden_field_tag(:subject, "#{current_user.profile.name} and #{@user.profile.name}") %>
						  <div>
						  	<br />
						 	<%= text_area_tag :body, nil, class: 'text_area border' %>
						 	<br />
						 </div>
						 <br />
			        </div>
			        <div class="modal-footer">
			            <button type="button" class="btn btn-custom" data-dismiss="modal" id=mynewpostclose>Close</button>
			            <%= submit_tag "Send", class: 'btn btn-purple' %>
			            <% end %>
			        </div>
		        </div>
		    </div>
		</div>
	<% end %>
</div>





<script>
	function modal() {
		var modal = document.getElementById('modal');
		modal.style.display = "block";
	}
</script>