config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :profiles do 
  	member do 
  		get :myprofile
  	end 
  end 

  root 'profiles#index'
  
  devise_for :users, 
  :controllers => {
                :registrations => "client/registrations"
            }
  resources :users

  resources :conversations do
  	resources :messages
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	def index
		@conversations = current_user.mailbox.conversations
	end

	def new 
		@user = User.find(params[:user])
	end

	def create 
		@recipient = User.find(params[:user])
		receipt = current_user.send_message(@recipient, params[:body], params[:subject])
		redirect_to conversation_path(receipt.conversation)
	end 

	def show
		@conversation = current_user.mailbox.conversations.find(params[:id])
	end  
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_message.html.erb
<% if @conversation.receipts_for(current_user).message.sender.profile.name==current_user.profile.name %>
		<div class="row white_background">	
			<div class="col-xs-6 col-xs-push-4 message_receiver"> 					
					<%= image_tag @conversation.receipts_for(current_user).message.sender.profile.image, class: 'message_image' %> 
					<h5><%= @conversation.receipts_for(current_user).message.sender.profile.name %></h5> 
					<p><%= @conversation.receipts_for(current_user).message.body %></p> 
				</div>
			</div>	
		<% else %>
			<div class="row white_background">	
				<div class="col-xs-6 col-xs-push-2 message_sender">  				
					<%= image_tag @conversation.receipts_for(current_user).message.sender.profile.image, class: 'message_image' %> 
					<h5><%= @conversation.receipts_for(current_user).message.sender.profile.name %></h5> 
					<p><%= @conversation.receipts_for(current_user).message.body %></p> 
				</div>
			</div> 
		<% end %> 

app/views/conversations/index.html.erb
<div class="col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2">
	<br /><br />
	<h3>Conversations</h3>
	<br />
    <br />
</div>
<% if current_user.mailbox.conversations.blank? %>
	<div class="col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2">
		<p><i>No conversations to display</i></p>
	</div>
<% end %>
<% @conversations.each do |conversation| %>
	<a href="conversations/<%= conversation.id %>">
	<div class="col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2 conversation"> 
		<h4 class="message_index_text"><%= conversation.subject %></h4></a>
	</div>
	</a>
<% end %> 
<div class="col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2 spacer">
</div>

app/views/conversations/new.html.erb
<div class="row">	
	<br />
	<div class="col-xs-10 col-xs-push-1 col-sm-8 col-sm-push-2 col-md-6 col-md-push-3 message_new"> 
		<div class="col-xs-10 col-xs-push-1">
			<h3>Contact <%= @user.profile.name %></h3>
				 <%= form_tag conversations_path, method: :post do %>
						<%= hidden_field_tag(:user, "#{@user.id}") %>
					  	<%= hidden_field_tag(:subject, "#{current_user.profile.name} and #{@user.profile.name}") %>
					  <div>
					  	<br />
					 	<%= text_area_tag :body, nil, class: 'text_area' %>
					 	<br />
					 </div>
					 <br />
					 <%= submit_tag "Send", class: 'btn btn-purple' %> 
				 <% end %>
			<br /><br />
		</div>		 
	</div>
</div>

app/views/conversations/show.html.erb
<div class="row white_background">
	<div class="col-xs-10 col-xs-push-1 col-sm-6 col-sm-push-3 white_background messages_background"> 
		<br/><br />
	</div>
</div>
<% @conversation.receipts_for(current_user).reverse.each do |r| %>
	<% if r.message.sender.profile.name==current_user.profile.name %>
	<div class="row white_background">	
		<div class="col-xs-6 col-xs-push-4 message_receiver"> 					
				<%= image_tag r.message.sender.profile.image, class: 'message_image' %> 
				<h5><%= r.message.sender.profile.name %></h5> 
				<p><%= r.message.body %></p> 
			</div>
		</div>	
	<% else %>
		<div class="row white_background">	
			<div class="col-xs-6 col-xs-push-2 message_sender">  				
				<%= image_tag r.message.sender.profile.image, class: 'message_image' %> 
				<h5><%= r.message.sender.profile.name %></h5> 
				<p><%= r.message.body %></p> 
			</div>
		</div> 
	<% end %> 
	 
<% end %>
<div class="row white_background">
	<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
</div> 
<div class="row message_input">	
		<div class="col-xs-10 col-xs-push-1 col-sm-6 col-sm-push-3">
			<%= form_tag conversation_messages_path(@conversation), method: :post do %>
				<div>
					<%= text_area_tag :body, nil, class: 'text_area' %>
				</div>
				<br />
				<%= submit_tag "Send", class: 'btn btn-purple' %> 
			<% end %> 
		</div>
</div>
<script>
	window.scroll(0, document.documentElement.scrollHeight)
</script>