config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :profiles do 
  	member do 
  		get :myprofile
  	end 
  end 

  root 'profiles#index'
  
  devise_for :users, 
  :controllers => {
                :registrations => "client/registrations"
            }
  resources :users

  resources :conversations do
  	resources :messages
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musi</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
	      <a class="navbar-brand" href="/"><%= image_tag "musilogo.png", class: 'logo' %></a>
	    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	       <% if user_signed_in? %>
	        <li><%= link_to "Home", profiles_path %></li>
	        	<% if current_user.profile.nil? %>
	        		<li><%= link_to "Create Profile", new_profile_path(current_user) %> </li>
	        	<% else %>
	        		<li><%= link_to "Profile", myprofile_profile_path(current_user) %></li>
	        	<% end %> 
	        	<li><%= link_to "Messages", conversations_path %></li>
	        	<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
	        <% else %>
	        	<li><%= link_to 'Login', new_user_session_path %></li>
	        	<li><%= link_to 'Register', new_user_registration_path %></li>
	        	<li><%= link_to 'Search', root_path %></li>
	        <% end %> 
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<div class="navbar_placeholder">
	</div>
  	<div class="container-fluid">
    	<%= yield %>
   </div>
  </body>
</html>